services:
  promptinel_app:
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
    volumes:
      - .:/app

  promptinel_node:
    profiles:
      - tooling
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
    volumes:
      - .:/app
